# Generated by Django 3.1.7 on 2021-04-12 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0001_initial'),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiareporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('total', models.FloatField(default=0)),
                ('diferencias', models.FloatField(default=0)),
                ('porcentaje', models.FloatField(default=0)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'exactitudes',
            },
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(max_length=300)),
                ('ncompra', models.CharField(max_length=100)),
                ('condicion', models.CharField(max_length=100)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_revisada', models.DateField(blank=True, null=True)),
                ('cliente', models.ManyToManyField(related_name='cliente', to='fac.Cliente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'envios',
            },
        ),
    ]
