# Generated by Django 3.1.7 on 2021-04-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
        ('inv', '0002_envio_historiareporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='cliente',
            field=models.ManyToManyField(related_name='Cliente_nombres', to='fac.Cliente'),
        ),
    ]
