# Generated by Django 3.1.7 on 2021-04-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20210412_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='envio',
        ),
    ]
