# Generated by Django 3.1.7 on 2021-04-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='cliente',
        ),
    ]
